name: integration-tests

env:
  TELEMETRY_ENABLED: false
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      reflex_dep:
        description: "Reflex dependency (full specifier)"

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  reflex-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install Requirements for reflex-web and reflex
        run: pip install -r requirements.txt
      - name: Init Website for reflex-web
        run: reflex init
      - name: Export the website
        run: reflex export
